isDevMode: &dev_mode true



url: 
  baseUri: "/"



doctrine: 
  driver:   "pdo_pgsql"
  host:     "localhost"
  user:     "pomelo"
  password: "pomelo"
  dbname:   "pomelo"



pheanstalk: 
  host: "localhost"
  port: "11300"



redis:
  host: "localhost"
  port: "6379"



twig:
  viewsDir: "views/"
  options:
    debug:            *dev_mode
    cache:            "/tmp/app/twig/"
    strict_variables: true

  whitelistedFunctions:
    - "number_format"
    - "round"
    - "substr"
    - "ucfirst"
    - "uclast"
    - "http_build_query"
    - "get_class"
    - "var_export"



annotations:
  cache: "/tmp/app/annotations/"



tag:
  titleSeparator: " | "



translator:
  locales:
    - en
    - fr
    - vn
    - ko
  fallbackLocales:
    - en



assets:
  css:
    cacheDir: "/tmp/app/css/"
    collections:
      main: "less/_.less"
  js:
    collections:
      footer:
        # Bootstrap
        - "node_modules/bootstrap/js/transition.js"
        - "node_modules/bootstrap/js/alert.js"
        - "node_modules/bootstrap/js/button.js"
        # - "node_modules/bootstrap/js/carousel.js"
        - "node_modules/bootstrap/js/collapse.js"
        - "node_modules/bootstrap/js/dropdown.js"
        - "node_modules/bootstrap/js/modal.js"
        # - "node_modules/bootstrap/js/tooltip.js"
        # - "node_modules/bootstrap/js/popover.js"
        # - "node_modules/bootstrap/js/scrollspy.js"
        # - "node_modules/bootstrap/js/tab.js"
        - "node_modules/bootstrap/js/affix.js"



console:
  commands: []



router:
  controllers:
    - "MyApp\\Controller\\IndexController"
    - "MyApp\\Controller\\ErrorController"
    - "MyApp\\Controller\\CssController"
    - "MyApp\\Controller\\JsController"

  notFound:
    controller: "MyApp\\Controller\\ErrorController"
    action:     "error404"

