isDevMode: &dev_mode true



url: 
  baseUri: "/"



doctrine: 
  driver:   "pdo_pgsql"
  host:     "postgres"
  user:     "postgres"
  password: ""
  dbname:   "postgres"



pheanstalk: 
  host: "beanstalkd"
  port: "11300"



redis:
  host: "redis"
  port: "6379"



twig:
  viewsDir: "views/"
  options:
    debug:            *dev_mode
    cache:            "/tmp/app/twig/"
    strict_variables: true

  whitelistedFunctions:
    - "number_format"
    - "round"
    - "substr"
    - "ucfirst"
    - "uclast"



annotations:
  cache: "/tmp/app/annotations/"



tag:
  titleSeparator: " | "



translator:
  locales:
    - en
    - fr
    - vn
    - ko
  fallbackLocales:
    - en



console:
  commands:
    - "MyApp\\Command\\Background\\ManagerCommand"
    - "MyApp\\Command\\Background\\RaiseCommand"
    - "MyApp\\Command\\Background\\WorkerCommand"



router:
  controllers:
    - "MyApp\\Controller\\IndexController"
    - "MyApp\\Controller\\ErrorController"

  notFound:
    controller: "MyApp\\Controller\\ErrorController"
    action:     "error404"
