isDevMode: &dev_mode true



url:
  baseUri: "/"



twig:
  viewsDir: "views/"
  options:
    debug:            *dev_mode
    cache:            "/tmp/app/twig/"
    strict_variables: true

  whitelistedFunctions:
    - "number_format"
    - "round"
    - "substr"
    - "ucfirst"
    - "uclast"



annotations:
  cache: "/tmp/app/annotations/"



tag:
  titleSeparator: " | "



console:
  commands:
    - "MyApp\\Command\\Background\\ManagerCommand"
    - "MyApp\\Command\\Background\\RaiseCommand"
    - "MyApp\\Command\\Background\\WorkerCommand"



router:
  controllers:
    - "MyApp\\Controller\\IndexController"
    - "MyApp\\Controller\\ErrorController"

  notFound:
    controller: "MyApp\\Controller\\ErrorController"
    action:     "error404"
