version: '3'
services:
  nginx:
    image: nginx:1-alpine
    links:
    - php
    ports:
        - "80:80"
    volumes:
        - .:/app/
        - ./deploy/site.conf:/etc/nginx/conf.d/site.conf
  php:
    image: php:7.3-fpm-alpine
    links:
    - postgres
    - redis
    - memcached
    - beanstalkd
    volumes:
        - .:/app/
  background:
    build: deploy/background/
    links:
    - postgres
    - redis
    - memcached
    - beanstalkd
    volumes:
        - .:/app/
  postgres:
    image: postgres:11
  redis:
    image: redis:5
  memcached:
    image: memcached:1
  beanstalkd:
    image: schickling/beanstalkd:latest
