version: '3'
services:
  nginx:
    image:    nginx:1-alpine
    restart:  on-failure
    env_file: .env
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/app/
      - ./deploy/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
  php:
    build:    deploy/php/
    restart:  on-failure
    env_file: .env
    links:
      - postgres
      - redis
      - beanstalkd
    volumes:
      - .:/app/
  background:
    build:    deploy/background/
    restart:  on-failure
    env_file: .env
    links:
      - nginx
      - postgres
      - redis
      - beanstalkd
    volumes:
      - .:/app/
  postgres:
    image:    postgres:11.4-alpine
    restart:  on-failure
    env_file: .env
  redis:
    image:    redis:5-alpine
    restart:  on-failure
    env_file: .env
  beanstalkd:
    image:    sidroberts/beanstalkd:1.11
    restart:  on-failure
    env_file: .env
