version: '3'
services:
  nginx:
    image: nginx:1-alpine
    links:
    - php
    ports:
        - "80:80"
    volumes:
        - .:/app/
        - ./deploy/nginx/site.conf:/etc/nginx/conf.d/site.conf
  php:
    build: deploy/php/
    links:
    - postgres
    - redis
    - memcached
    - beanstalkd
    volumes:
        - .:/app/
  background:
    build: deploy/background/
    links:
    - nginx
    - postgres
    - redis
    - memcached
    - beanstalkd
    volumes:
        - .:/app/
  postgres:
    image: postgres:11-alpine
  redis:
    image: redis:5-alpine
  memcached:
    image: memcached:1-alpine
  beanstalkd:
    image: schickling/beanstalkd:latest
